### ISSUE TITLE
Adding responsiveness to all pages

### ISSUE THREAD

**Issue by saurabhhirugade** [Webmaster-WCE/WCE-Connects#8]
Currently, the viewport is fixed to 1024 width.
Change the meta tag to \<meta name="viewport" content="width=device-width, initial-scale=1.0"\> in index.html
And add breakpoints ( for small, medium, and large screens )
Style all pages according to breakpoints

**Comment by saurabhhirugade** [comment]
Breakpoints Guide
Small = Up to 640px
Medium = 641 - 1007px
Large = 1008px and up

**Comment by OnkarGavali** [comment]
Added responsiveness to all existing components
